// @ts-nocheck
namespace Ivent {
  const glEsc = (v) => String(v ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  const glList = (v) => Array.isArray(v) ? v : [];
  const glActive = (lib) => Object.values(lib.manifests).filter((m:any)=>m.active && !m.historical).sort((a:any,b:any)=>a.name.localeCompare(b.name,'ru'));
  const glArchived = (lib) => Object.values(lib.manifests).filter((m:any)=>!m.active && !m.historical).sort((a:any,b:any)=>a.name.localeCompare(b.name,'ru'));
  function getActiveGameModuleIds(lib) { return glActive(lib).map((m:any)=>m.moduleId); }
  function glCard(m, archived) {
    return `<article class="gl-card" data-gl-module="${glEsc(m.moduleId)}"><div class="gl-cover"><img src="${glEsc(m.cover||defaultGameCover(m))}"><b>${m.source==='system'?'СИСТЕМНАЯ':`СВОЯ · v${m.revision}`}</b></div><div class="gl-body"><h3>${glEsc(m.name)}</h3><p>${glEsc(m.summary||m.rules)}</p><div class="gl-meta">👥 ${m.minPlayers}–${m.maxPlayers} · ⏱ ${m.estimatedMinutes} мин${glList(m.aiCapabilities).length?' · ✦ ИИ':''}</div><div class="button-row">${archived?'':`<button class="btn primary" data-gl-action="add-stage" data-module="${glEsc(m.moduleId)}">Добавить этап</button>`}<button class="btn" data-gl-action="passport" data-module="${glEsc(m.moduleId)}">Паспорт</button>${m.source==='custom'?`<button class="btn ghost" data-gl-action="edit" data-module="${glEsc(m.moduleId)}">Изменить</button>`:''}<button class="btn ghost" data-gl-action="duplicate" data-module="${glEsc(m.moduleId)}">Дублировать</button><button class="btn ${archived?'primary':'ghost'}" data-gl-action="${archived?'restore':'archive'}" data-module="${glEsc(m.moduleId)}">${archived?'Вернуть':'В архив'}</button></div></div></article>`;
  }
  function renderGameLibraryHtml(lib) {
    const active=glActive(lib), archived=glArchived(lib);
    return `<main class="workspace gl-library"><div class="workspace-head"><div><small class="gl-kicker">IVENT GAME LIBRARY</small><h1 class="workspace-title">Игры</h1><p class="workspace-sub">Активные игры доступны для новых этапов. Архивные остаются в истории и сохранениях.</p></div><button class="btn primary" data-gl-action="create">＋ Создать игру</button></div><h2>Активные <span class="tiny-pill">${active.length}</span></h2><div class="gl-grid">${active.map((m:any)=>glCard(m,false)).join('')}</div><h2 class="gl-archive-title">Архив <span class="tiny-pill">${archived.length}</span></h2><div class="gl-grid">${archived.map((m:any)=>glCard(m,true)).join('')||'<div class="card">Архив пуст</div>'}</div></main>`;
  }
  function glResult(mode) { return ({'single-winner':'1 победитель','winners':'несколько победителей','winners-and-loser':'победители + проигравший','single-loser':'1 проигравший','ranking':'рейтинг','manual':'вручную','auction':'аукцион','none':'без результата'} as any)[mode]||mode||'вручную'; }
  function renderGamePassportHtml(m) {
    return `<div class="gl-passport"><img class="gl-pass-cover" src="${glEsc(m.cover||defaultGameCover(m))}"><small class="gl-kicker">GAME MANIFEST · v${m.revision}</small><h2>${glEsc(m.name)}</h2><p>${glEsc(m.summary||m.rules)}</p><div class="gl-stats"><span><b>${m.minPlayers}–${m.maxPlayers}</b> игроков</span><span><b>${m.estimatedMinutes}</b> минут</span><span><b>${m.defaultWinnerReward}</b> жет. награда</span></div><div class="gl-pass-grid"><section><h3>Цель</h3><p>${glEsc(m.goal||'Определяется правилами игры.')}</p><h3>Правила</h3><p>${glEsc(m.rules).replace(/\n/g,'<br>')}</p></section><aside><h3>Результат</h3><p>${glEsc(glResult(m.resultMode))}</p><h3>Предметы</h3><p>${m.itemsPolicy==='forbidden'?'Запрещены':m.itemsPolicy==='before-after'?'Только до / после':'Разрешены'}</p><h3>Реквизит</h3><p>${glEsc(glList(m.requiredProps).join(', ')||'Не требуется')}</p><h3>ИИ</h3><p>${glEsc(glList(m.aiCapabilities).join(', ')||'Не используется')}</p>${m.hostNotes?`<h3>Ведущему</h3><p>${glEsc(m.hostNotes)}</p>`:''}</aside></div></div>`;
  }
  function renderGameEditorHtml(m, createAndAdd=false) {
    const x=m||{}, ai=new Set(glList(x.aiCapabilities)), ck=(id)=>ai.has(id)?'checked':'';
    return `<div class="gl-editor" data-gl-create-add="${createAndAdd?'1':'0'}" data-gl-edit-module="${glEsc(m?.moduleId||'')}"><div class="gl-editor-head"><div><small class="gl-kicker">GAME MANIFEST</small><h2>${m?'Редактор игры':'Новая игра'}</h2></div><button class="gl-x" data-gl-action="close-modal">×</button></div><div class="gl-edit-grid"><section><label>Название *<input class="input" id="gl-name" value="${glEsc(x.name||'')}"></label><label>Короткая суть *<textarea class="input" id="gl-summary">${glEsc(x.summary||'')}</textarea></label><label>Цель<textarea class="input" id="gl-goal">${glEsc(x.goal||'')}</textarea></label><label>Правила *<textarea class="input gl-rules-input" id="gl-rules">${glEsc(x.rules||'')}</textarea></label><label>Заметка ведущему<textarea class="input" id="gl-host-notes">${glEsc(x.hostNotes||'')}</textarea></label></section><aside><div class="gl-image"><img id="gl-cover-preview" src="${glEsc(x.cover||'')}"><div><b>Картинка 16:9</b><small>800×450 после обработки</small><input type="file" id="gl-cover-file" accept="image/*"></div></div><div class="gl-two"><label>Игроков от<input class="input" id="gl-min" type="number" min="1" value="${x.minPlayers||2}"></label><label>до<input class="input" id="gl-max" type="number" min="1" value="${x.maxPlayers||30}"></label></div><div class="gl-two"><label>Время, мин<input class="input" id="gl-minutes" type="number" min="1" value="${x.estimatedMinutes||10}"></label><label>Награда<input class="input" id="gl-reward" type="number" min="0" value="${x.defaultWinnerReward??4}"></label></div><label>Результат<select class="select" id="gl-result"><option value="single-winner">Один победитель</option><option value="winners">Несколько победителей</option><option value="single-loser">Один проигравший</option><option value="ranking">Рейтинг</option><option value="manual">Вручную</option></select></label><label>Предметы<select class="select" id="gl-items"><option value="allowed">Разрешены</option><option value="before-after">До / после</option><option value="forbidden">Запрещены</option></select></label><label>Реквизит<input class="input" id="gl-props" value="${glEsc(glList(x.requiredProps).join(', '))}"></label><label>Теги<input class="input" id="gl-tags" value="${glEsc(glList(x.tags).join(', '))}"></label><div class="gl-ai"><b>ИИ</b><label><input type="checkbox" data-gl-ai="text" ${ck('text')}> текст</label><label><input type="checkbox" data-gl-ai="image" ${ck('image')}> изображение</label><label><input type="checkbox" data-gl-ai="judge" ${ck('judge')}> судья</label><label><input type="checkbox" data-gl-ai="voice" ${ck('voice')}> голос</label><label><input type="checkbox" data-gl-ai="task" ${ck('task')}> задания</label></div></aside></div><div class="button-row gl-save-row"><button class="btn primary" data-gl-action="save-game">${createAndAdd?'Создать и добавить этап':m?'Сохранить новую версию':'Создать игру'}</button><button class="btn" data-gl-action="close-modal">Отмена</button></div></div>`;
  }
  function glStyles(doc) {
    if(doc.getElementById('gl-styles'))return;const s=doc.createElement('style');s.id='gl-styles';s.textContent=`.gl-kicker{letter-spacing:.16em;font-size:10px;opacity:.55}.gl-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(285px,1fr));gap:15px}.gl-card{background:#141923;border:1px solid #283040;border-radius:18px;overflow:hidden}.gl-cover{aspect-ratio:16/9;position:relative}.gl-cover img{width:100%;height:100%;object-fit:cover}.gl-cover b{position:absolute;left:10px;top:10px;background:#080a0dcc;padding:6px 8px;border-radius:99px;font-size:9px;letter-spacing:.08em}.gl-body{padding:15px}.gl-body h3{font-size:20px;margin:0 0 6px}.gl-body p{color:#aab5c4;min-height:40px}.gl-meta{font-size:12px;color:#9ca8b8;margin:10px 0}.gl-card .btn{padding:8px 9px;font-size:11px}.gl-archive-title{margin-top:34px}.gl-modal-bg{position:fixed;inset:0;z-index:10020;background:#030409cc;backdrop-filter:blur(10px);display:grid;place-items:center;padding:22px}.gl-modal{background:#151a24;border:1px solid #303949;border-radius:22px;padding:22px;width:min(1050px,96vw);max-height:92vh;overflow:auto}.gl-modal.small{width:min(800px,96vw)}.gl-pass-cover{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:15px}.gl-passport h2,.gl-editor h2{font-size:30px;margin:6px 0}.gl-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0}.gl-stats span{padding:12px;background:#ffffff0d;border-radius:12px}.gl-stats b{font-size:20px}.gl-pass-grid,.gl-edit-grid{display:grid;grid-template-columns:1.25fr 1fr;gap:18px}.gl-pass-grid>*{background:#ffffff08;border-radius:14px;padding:14px}.gl-editor-head{display:flex;justify-content:space-between}.gl-x{background:none;color:white;font-size:30px;border:0}.gl-editor label{display:block;font-size:11px;font-weight:700;margin:0 0 10px}.gl-editor textarea{min-height:65px;resize:vertical}.gl-editor .gl-rules-input{min-height:160px}.gl-two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.gl-image{display:grid;grid-template-columns:125px 1fr;gap:10px;border:1px dashed #394556;padding:9px;border-radius:13px;margin-bottom:12px}.gl-image img{width:125px;aspect-ratio:16/9;object-fit:cover;background:#202632;border-radius:9px}.gl-image small{display:block;color:#8794a6;margin:4px 0 8px}.gl-ai{display:flex;gap:8px;flex-wrap:wrap}.gl-ai label{font-size:12px}.gl-save-row{justify-content:flex-end}.gl-stage-cover{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:12px;margin-bottom:10px}.gl-hero-cover{width:150px;aspect-ratio:16/9;object-fit:cover;border-radius:13px;float:right;margin:0 0 10px 15px}@media(max-width:800px){.gl-pass-grid,.gl-edit-grid{grid-template-columns:1fr}}`;doc.head.appendChild(s);
  }
  function glModal(doc,html,small=false){doc.querySelector('.gl-modal-bg')?.remove();const b=doc.createElement('div');b.className='gl-modal-bg';b.innerHTML=`<div class="gl-modal ${small?'small':''}">${html}</div>`;doc.body.appendChild(b);return b;}
  const glLib=()=>loadGameLibrary();
  function glPersist(lib){const saved=saveGameLibrary(lib);registerLibraryModules(saved);return saved;}
  function glManifest(id){return glLib().manifests[id]||null;}
  function glByTitle(title){const t=String(title||'').replace(/^\d+\.\s*/,'').trim();return Object.values(glLib().manifests).find((m:any)=>m.name===t)||null;}
  function glRenderLibrary(doc){const shell=doc.querySelector('.app-shell');if(!shell)return;shell.querySelector('main')?.remove();const nav=shell.querySelector('.nav'),h=doc.createElement('div');h.innerHTML=renderGameLibraryHtml(glLib());shell.insertBefore(h.firstElementChild,nav||null);shell.querySelectorAll('.nav-btn').forEach((x:any)=>x.classList.remove('active'));shell.querySelector('.gl-nav')?.classList.add('active');}
  function glEnhance(doc){const nav=doc.querySelector('.nav');if(nav&&!nav.querySelector('.gl-nav')){const b=doc.createElement('button');b.className='nav-btn gl-nav';b.dataset.glAction='open-library';b.textContent='Игры';nav.insertBefore(b,nav.children[1]||null);}const sel=doc.getElementById('new-stage-module');if(sel){const active=new Set(getActiveGameModuleIds(glLib()));Array.from((sel as HTMLSelectElement).options).forEach((o:any)=>{if(!active.has(o.value))o.remove();});const row=sel.parentElement;if(row&&!row.querySelector('[data-gl-action="quick-create"]')){const b=doc.createElement('button');b.className='btn purple';b.dataset.glAction='quick-create';b.textContent='＋ Новая игра';row.appendChild(b);}doc.querySelectorAll('.workspace .card').forEach((c:any)=>{if(c.querySelector('.gl-stage-cover'))return;const m=glByTitle(c.querySelector('h3')?.textContent);if(!m)return;const img=doc.createElement('img');img.className='gl-stage-cover';img.src=m.cover||defaultGameCover(m);c.prepend(img);});}const hero=doc.querySelector('.hero-stage');if(hero&&!hero.querySelector('.gl-hero-cover')){const m=glByTitle(hero.querySelector('.stage-title')?.textContent);if(m){const img=doc.createElement('img');img.className='gl-hero-cover';img.src=m.cover||defaultGameCover(m);hero.prepend(img);}}}
  function glAddStage(doc,moduleId){doc.querySelector('[data-view="program"]')?.click();setTimeout(()=>{glEnhance(doc);const s:any=doc.getElementById('new-stage-module');if(!s)return;s.value=moduleId;doc.querySelector('[data-action="add-stage"]')?.click();},0);}
  function glOpenEditor(doc,m=null,createAndAdd=false){const modal:any=glModal(doc,renderGameEditorHtml(m,createAndAdd));if(m){modal.querySelector('#gl-result').value=m.resultMode;modal.querySelector('#gl-items').value=m.itemsPolicy;}modal.__cover=m?.cover||'';}
  const glCsv=(v)=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
  async function glSaveEditor(doc,btn){const modal:any=btn.closest('.gl-modal-bg'),ed=modal?.querySelector('.gl-editor');if(!modal||!ed)return;const v=(id)=>modal.querySelector(`#${id}`)?.value??'';const input={name:v('gl-name'),summary:v('gl-summary'),goal:v('gl-goal'),rules:v('gl-rules'),hostNotes:v('gl-host-notes'),minPlayers:+v('gl-min'),maxPlayers:+v('gl-max'),estimatedMinutes:+v('gl-minutes'),defaultWinnerReward:+v('gl-reward'),resultMode:v('gl-result'),itemsPolicy:v('gl-items'),mode:'individual',requiredProps:glCsv(v('gl-props')),tags:glCsv(v('gl-tags')),aiCapabilities:Array.from(modal.querySelectorAll('[data-gl-ai]:checked')).map((x:any)=>x.dataset.glAi),cover:modal.__cover||''};let lib=glLib(),manifest;const id=ed.dataset.glEditModule;if(id){const out=reviseGameManifest(lib,id,input);lib=out.library;manifest=out.manifest;}else{manifest=createCustomGameManifest(input);lib=upsertGameManifest(lib,manifest);}glPersist(lib);modal.remove();ed.dataset.glCreateAdd==='1'?glAddStage(doc,manifest.moduleId):glRenderLibrary(doc);}
  function installGameLibraryUI(doc,win){if(!doc||doc.documentElement?.dataset.glInstalled==='1')return;doc.documentElement.dataset.glInstalled='1';glStyles(doc);glPersist(glLib());registerLibraryModules(glLib());installGameLibraryGuards();installLibraryStorageBundle();doc.addEventListener('click',async(e:any)=>{const t=e.target.closest?.('[data-gl-action]');if(!t)return;const a=t.dataset.glAction,id=t.dataset.module;if(a==='open-library'){e.preventDefault();glRenderLibrary(doc);}else if(a==='create')glOpenEditor(doc);else if(a==='quick-create')glOpenEditor(doc,null,true);else if(a==='close-modal')t.closest('.gl-modal-bg')?.remove();else if(a==='passport'){const m=glManifest(id);if(m)glModal(doc,renderGamePassportHtml(m),true);}else if(a==='archive'||a==='restore'){glPersist(setGameActive(glLib(),id,a==='restore'));glRenderLibrary(doc);}else if(a==='duplicate'){glPersist(duplicateGameManifest(glLib(),id).library);glRenderLibrary(doc);}else if(a==='edit'){const m=glManifest(id);if(m)glOpenEditor(doc,m);}else if(a==='add-stage')glAddStage(doc,id);else if(a==='save-game'){try{await glSaveEditor(doc,t);}catch(err){win.alert?.(err.message||String(err));}}},true);doc.addEventListener('change',async(e:any)=>{const i=e.target;if(i?.id!=='gl-cover-file'||!i.files?.[0])return;const modal:any=i.closest('.gl-modal-bg');try{const cover=await readAndResizeGameCover(i.files[0],doc);modal.__cover=cover;modal.querySelector('#gl-cover-preview').src=cover;}catch(err){win.alert?.(err.message||String(err));}});new MutationObserver(()=>glEnhance(doc)).observe(doc.getElementById('app')||doc.body,{subtree:true,childList:true});setTimeout(()=>glEnhance(doc),0);}
  Ivent.renderGameLibraryHtml=renderGameLibraryHtml;Ivent.renderGamePassportHtml=renderGamePassportHtml;Ivent.renderGameEditorHtml=renderGameEditorHtml;Ivent.getActiveGameModuleIds=getActiveGameModuleIds;Ivent.installGameLibraryUI=installGameLibraryUI;
}
